command: ["uvicorn", "app:app"]

env:
  - name: 'DATABRICKS_REFERENCE_CATOLOG'
    value: '_data'
  - name: 'DATABRICKS_REFERENCE_SCHEMA'
    value: 'lineage'
  - name: 'DATABRICKS_WAREHOUSE_PATH'
    value: '/sql/1.0/warehouses/{your_warehouse_id}'